#!/bin/bash

# Reconfigure logger services of select workers

set -e
#set -x

# Load parameters of the setup into the corresponding environment
# variables

. $(dirname "$0")/config/env

if [ -n "${CZAR_DB}" ]; then
    ssh -n $MASTER 'rm -vf '${QSERV_BASE_DIR}'/master/log/czar-mariadb/*.log'&
fi
if [ -n "${CZAR_PROXY}" ]; then
    ssh -n $MASTER 'rm -vf '${QSERV_BASE_DIR}'/master/log/mysql-proxy/*.log'&
    ssh -n $MASTER 'rm -vf '${QSERV_BASE_DIR}'/master/log/czar-proxy/*.log'&
fi
if [ -n "${CZAR_SSL_PROXY}" ]; then
    ssh -n $MASTER 'rm -vf '${QSERV_BASE_DIR}'/master/log/czar-ssl-proxy/*.log'&
fi
if [ -n "${CZAR_HTTP}" ]; then
    ssh -n $MASTER 'rm -vf '${QSERV_BASE_DIR}'/master/log/czar-http/*.log'&
fi
if [ -n "${WORKER_DB}" ]; then
  for WORKER in $WORKERS; do
    ssh -n $WORKER 'rm -vf '${QSERV_BASE_DIR}'/worker/log/worker-mariadb/*.log'&
  done
fi
if [ -n "${WORKER_SVC}" ]; then
  for WORKER in $WORKERS; do
    ssh -n $WORKER 'rm -vf '${QSERV_BASE_DIR}'/worker/log/worker-svc/*.log'&
  done
fi
if [ -n "${REPL_DB}" ]; then
    ssh -n $MASTER 'rm -vf '${QSERV_BASE_DIR}'/master/log/repl-mariadb/*.log'&
fi
if [ -n "${REPL_REG}" ]; then
    ssh -n $MASTER 'rm -vf '${QSERV_BASE_DIR}'/master/log/repl-reg/*.log'&
fi
if [ -n "${REPL_CONTR}" ]; then
    ssh -n $MASTER 'rm -vf '${QSERV_BASE_DIR}'/master/log/repl-contr/*.log'&
fi
if [ -n "${REPL_WORKER}" ]; then
  for WORKER in $WORKERS; do
    ssh -n $WORKER 'rm -vf '${QSERV_BASE_DIR}'/worker/log/repl-worker/*.log'&
  done
fi
wait
