#!/bin/bash

# List core dump files of the select services

set -e

# Load parameters of the setup into the corresponding environment
# variables

. $(dirname "$0")/config/env

function core_files_ls {
    local SERVER=$1
    local HOST=$2
    local CONTAINER_NAME=$3
    local CORE_FILES_DIR=${QSERV_BASE_DIR}/${SERVER}/core-files/${CONTAINER_NAME}
    ssh -n $HOST 'sudo -u qserv ls -l '"${CORE_FILES_DIR}/core.*" 2>/dev/null | awk '{print "  "$0}' > /dev/tty
}

echo
echo "[${MASTER}]"
if [ -n "${CZAR_CMSD}" ]; then
  echo
  core_files_ls master ${MASTER} ${CZAR_CMSD_CONTAINER_NAME}
fi
if [ -n "${CZAR_XROOTD}" ]; then
  echo
  core_files_ls master ${MASTER} ${CZAR_XROOTD_CONTAINER_NAME}
fi
if [ -n "${CZAR_PROXY}" ]; then
  echo
  core_files_ls master ${MASTER} ${CZAR_PROXY_CONTAINER_NAME}
fi
if [ -n "${REPL_REG}" ]; then
  echo
  core_files_ls master ${MASTER} ${REPL_REG_CONTAINER_NAME}
fi
if [ -n "${REPL_CONTR}" ]; then
  echo
  core_files_ls master ${MASTER} ${REPL_CONTR_CONTAINER_NAME}
fi
for WORKER in $WORKERS; do
  echo
  echo "[${WORKER}]"
  if [ -n "${WORKER_CMSD}" ]; then
    echo
    core_files_ls worker ${WORKER} ${WORKER_CMSD_CONTAINER_NAME}
  fi
  if [ -n "${WORKER_XROOTD}" ]; then
    echo
    core_files_ls worker ${WORKER} ${WORKER_XROOTD_CONTAINER_NAME}
  fi
  if [ -n "${REPL_WORKER}" ]; then
    echo
    core_files_ls worker ${WORKER} ${REPL_WORKER_CONTAINER_NAME}
  fi
done
echo
