#!/bin/bash

# Reconfigure logger services of select workers

set -e

# Load parameters of the setup into the corresponding environment
# variables

. $(dirname "$0")/config/env

if [ -n "${CZAR_CMSD}" ]; then
    update_config_master ${QSERV_BASE_DIR}/config-etc/log/cmsd.cfg
fi
if [ -n "${CZAR_XROOTD}" ]; then
    update_config_master ${QSERV_BASE_DIR}/config-etc/log/xrootd.cfg
fi
if [ -n "${CZAR_PROXY}" ]; then
    update_config_master ${QSERV_BASE_DIR}/config-etc/log/proxy.cfg
fi
if [ -n "${WORKER_CMSD}" ]; then
    update_config ${QSERV_BASE_DIR}/config-etc/log/cmsd.cfg
fi
if [ -n "${WORKER_XROOTD}" ]; then
    update_config ${QSERV_BASE_DIR}/config-etc/log/xrootd.cfg
fi
if [ -n "${REPL_CONTR}" ]; then
    update_config_master ${REPL_BASE_DIR}/config/log4cxx.replication.properties
fi
if [ -n "${REPL_WORKER}" ]; then
    update_config ${REPL_BASE_DIR}/config/log4cxx.replication.properties
fi
