#!/bin/bash

# Reconfigure logger services of select workers

set -e
#set -x

# Load parameters of the setup into the corresponding environment
# variables

. $(dirname "$0")/config/env

if [ -n "${CZAR_DB}" ]; then
    ssh -n $MASTER 'rm -vf '${QSERV_BASE_DIR}'/master/log/'${CZAR_DB_CONTAINER_NAME}'.*.log'&
fi
if [ -n "${CZAR_CMSD}" ]; then
    ssh -n $MASTER 'rm -vf '${QSERV_BASE_DIR}'/master/log/'${CZAR_CMSD_CONTAINER_NAME}'.log'&
fi
if [ -n "${CZAR_XROOTD}" ]; then
    ssh -n $MASTER 'rm -vf '${QSERV_BASE_DIR}'/master/log/'${CZAR_XROOTD_CONTAINER_NAME}'.log'&
fi
if [ -n "${CZAR_PROXY}" ]; then
    ssh -n $MASTER 'rm -vf '${QSERV_BASE_DIR}'/master/log/'${CZAR_PROXY_CONTAINER_NAME}'.mysql-proxy.log'&
    ssh -n $MASTER 'rm -vf '${QSERV_BASE_DIR}'/master/log/'${CZAR_PROXY_CONTAINER_NAME}'.log'&
fi
if [ -n "${WORKER_DB}" ]; then
  for WORKER in $WORKERS; do
    ssh -n $WORKER 'rm -vf '${QSERV_BASE_DIR}/worker/log'/'${WORKER_DB_CONTAINER_NAME}'.*.log'&
  done
fi
if [ -n "${WORKER_CMSD}" ]; then
  for WORKER in $WORKERS; do
    ssh -n $WORKER 'rm -vf '${QSERV_BASE_DIR}/worker/log'/'${WORKER_CMSD_CONTAINER_NAME}'.log'&
  done
fi
if [ -n "${WORKER_XROOTD}" ]; then
  for WORKER in $WORKERS; do
    ssh -n $WORKER 'rm -vf '${QSERV_BASE_DIR}/worker/log'/'${WORKER_XROOTD_CONTAINER_NAME}'.log'&
  done
fi
if [ -n "${REPL_DB}" ]; then
    ssh -n $MASTER 'rm -vf '${QSERV_BASE_DIR}'/master/log/'${REPL_DB_CONTAINER_NAME}'.*.log'&
fi
if [ -n "${REPL_REG}" ]; then
    ssh -n $MASTER 'rm -vf '${QSERV_BASE_DIR}'/master/log/'${REPL_REG_CONTAINER_NAME}'.log'&
fi
if [ -n "${REPL_CONTR}" ]; then
    ssh -n $MASTER 'rm -vf '${QSERV_BASE_DIR}'/master/log/'${REPL_CONTR_CONTAINER_NAME}'.log'&
fi
if [ -n "${REPL_WORKER}" ]; then
  for WORKER in $WORKERS; do
    ssh -n $WORKER 'rm -vf '${QSERV_BASE_DIR}/worker/log'/'${REPL_WORKER_CONTAINER_NAME}'.log'&
  done
fi
wait
