#!/bin/bash

# Reconfigure logger services of select workers

set -e

# Load parameters of the setup into the corresponding environment
# variables

. $(dirname "$0")/config/env

if [ -n "${CZAR_PROXY}" ]; then
    update_config_master ${QSERV_BASE_DIR}/master/config/log/proxy.cfg
fi
if [ -n "${CZAR_HTTP}" ]; then
    update_config_master ${QSERV_BASE_DIR}/master/config/log/czar-http.cfg
fi
if [ -n "${WORKER_SVC}" ]; then
    update_config ${QSERV_BASE_DIR}/worker/config/log/worker-svc.cfg
fi
if [ -n "${REPL_REG}" ]; then
    update_config_master ${QSERV_BASE_DIR}/master/config/log/repl-reg.cfg
fi
if [ -n "${REPL_CONTR}" ]; then
    update_config_master ${QSERV_BASE_DIR}/master/config/log/repl-contr.cfg
fi
if [ -n "${REPL_WORKER}" ]; then
    update_config ${QSERV_BASE_DIR}/worker/config/log/repl-worker.cfg
fi
