#!/bin/bash

# Remove core files of the select services

set -e

# Load parameters of the setup into the corresponding environment
# variables

. $(dirname "$0")/config/env

if [ -n "${CZAR_DB}${CZAR_PROXY}${CZAR_SSL_PROXY}${CZAR_HTTP}${REPL_DB}${REPL_REG}${REPL_CONTR}" ]; then
  echo
  echo "[${MASTER}]"
  echo
  ssh -n $MASTER 'rm -vf '"${CORE_DUMPS}/core.*" 2>/dev/null | awk '{print "  "$0}'
fi
if [ -n "${WORKER_DB}${WORKER_SVC}${REPL_WORKER}" ]; then
  for WORKER in $WORKERS; do
    echo
    echo "[${WORKER}]"
    echo
    ssh -n $WORKER 'rm -vf '"${CORE_DUMPS}/core.*" 2>/dev/null | awk '{print "  "$0}'
  done
fi
echo
